### ISSUE TITLE
galcore headers

### ISSUE THREAD

**Issue by danboid** [etnaviv/libetnaviv#1]
I built libetnaviv last night but I was only able to do so because I was lucky enough to catch someone in #etnaviv on Freenode who gave me a patch that provided the galcore headers. The problem here is that even they couldn't remember where they got the headers from, only that they had a hell of a time tracking them down.

It would be nice if the README explained how to obtain the galcore headers if they can't just be included? They're GPL licensed it seems.

https://raw.githubusercontent.com/d4ddi0/meta-etnaviv/master/recipes-graphics/etnaviv/libetnaviv/libetnaviv.patch

**Comment by laanwj** [comment]
There is a repository of historical galcore kernel headers under
https://github.com/etnaviv - however unless you're reverse engineering the
Vivante stuff you shouldn't need them.

If that is your goal: The Vivante kernel interface has zero slack with
regard to backwards/forwards compatibility. It breaks even between
revisions. So always use the ones from your kernel instead of random ones
you find on the internet!

Etnaviv, on the other hand, nowadays has its own kernel driver and
interface which is part of mainline linux and libdrm. "Libetnaviv" is an
early revision of the libdrm stuff that still used Vivante's kernel driver.
It is a dead end

**Comment by danboid** [comment]
Hi laanwj

No reverse engineering here - just someone who wants to use armada and etnaviv on a SABRE Lite under Arch.

xf86-video-armada required libetnaviv to build with etnaviv acceleration. I had already built and install mesa git (17.1) with the etnaviv and imx gallium drivers but apparently that wasnt enough. I did look in the etna_viv repo but that seemed to just be RE and debug tools - no use to me. Building and installing libetnaviv did seem to satisfy armada's requirements for enabling etnaviv accel.

Is xf86-video-armada outdated then?

**Comment by danboid** [comment]
I used this command to clone armada:

`clone -b unstable-devel http://git.arm.linux.org.uk/cgit/xf86-video-armada.git/`

and I only cloned it a few days ago so it should be up-to-date so I don't understand how what you say clashes with what its configure script says. Should it not ask for libetnaviv to enable etnaviv support any more? If I do still need it, where is the code I should build?

Thanks

**Comment by austriancoder** [comment]
xf86-video-armada needs to get improved to not use galcor headers and not libetnaviv but libdrm-etnaviv or even use directly the etnaviv kernel driver. Keep in mind that there is no released version of xf86-video-armada that supports etnaviv - all work does in a branch called 'unstable-devel'.

So if you have some free time start hacking on it :)

But as a fast solution simpliy checkout 3815bcc09ccef173987f2d346a947a9b7e502762 from https://github.com/etnaviv/etna_viv.git and it should work as pointed out in the README of xf86-video-armada.

**Comment by danboid** [comment]
Hi  austriancoder

"It should work as pointed out"...

As I said, I've already looked at that etna_viv repo you mention but I couldn't see any libraries within it. I could see some header files so maybe armada wants them but what about libetnaviv? You say armada needs to be updated not to check for that now, right?

Are there some sufficiently verbose and up-to-date instructions for building xf86-video-armada with etnaviv support anywhere?

Thanks

**Comment by austriancoder** [comment]
I will build xf86-video-armada the next hour and will publish a blog post as how to. I have a jenkins build job for it so I know its do-able.

**Comment by danboid** [comment]
Thanks austriancoder - that'd be a big help!

**Comment by laanwj** [comment]
> As I said, I've already looked at that etna_viv repo you mention but I couldn't see any libraries within it. I could see some header files so maybe armada wants them but what about libetnaviv?

All the library stuff that was in that repository has been moved to `attic/`, or other repositories. It is meant now only for hosting the RE-ing information and tools, and it the generated rnndb (hardware) header files in `src/include`. Projects that use these should ideally include them into their tree and update them only as necessary (to avoid breakages by e.g. fields that are renamed due to new discoveries). I hope xf86-video-armada will soon.

**Comment by danboid** [comment]
I hope you've not encountered any showstoppers to writing your blog post @austriancoder ?

**Comment by austriancoder** [comment]
Hope it works for you - if not tell it and I will help you and improve the blog post.
https://www.christian-gmeiner.info/2017/02/10/compiling-armada-ddx-with-etnaviv-support/

**Comment by danboid** [comment]
Hi austriancoder!

Thanks for writing that guide. I'm sure I'm getting closer now.

I've tried it but X is crashing when trying to load MATE. I'll try it it with Fluxbox now to see if I have any more luck, but first the feedback on your blog post! 

The first and only really major thing I think is missing from your blog post is the mesa info, mainly:

* Minimum mesa version required for etnaviv support (17/git)

* Key mesa configure options, which I believe to be:

`--with-gallium-drivers=etnaviv,imx`

Are there any other key mesa configure options for etnaviv users?

If any users are using pre-built mesa 17+ binaries, is there any easy way to check mesa is built correctly if you can't find the options that were used to build your package?

Why do users have to download an older etna_viv? The latest code is broken / experimental?

Do all users use the GCABI=imx6_v4_6_9 build option or does that need to be adjusted depending on kernel version?

Last but not least, why is armada compiled with --disable-etnaviv if we want etnaviv acceleration?

Thanks!

**Comment by danboid** [comment]
I have got fluxbox to start under armada but only at 720x480 on a 4K display. I tried using xrandr to set it to 1920x1080 but it crashed.

I'll post some logs in a new ticket somewhere.

**Comment by laanwj** [comment]
Thanks for writing the guide, but I don't understand how that can even work, hardcoding the GCABI
```
make GCABI=imx6_v4_6_9
```
Does this only work with a specific kernel version?

**Comment by danboid** [comment]
Also, please add the minimum kernel version required.

**Comment by danboid** [comment]
I've had a reply from RMK which has explained to me why --disable-etnaviv is used to configure
armada. etnaviv is the non-drm driver but I I want to (did) build armada for etnadrm.

**Comment by austriancoder** [comment]
I had to build libetnaviv as the lack of viv_open disabled etnadrm support. rmk landed some commits to fix all of this stuff and now you really just need to follow the instructions in the README.
As a result of this I kicked my blog post as there is no need for it now.

**Comment by danboid** [comment]
Nope - I'm back to the OP prob.

I pulled the latest etna_viv and checked out armada afresh but when I run the autogen command given in the armada README ie

`./autogen.sh --prefix=/usr --disable-vivante --disable-etnaviv --with-etnaviv-source=$ETNA_SRC`

(and after exporting ETNA_SRC as required)

configure fails because the libGAL headers are missing. As I understand it, that autogen command should be building for etnadrm and hence shouldn't require libGAL, right?

**Comment by danboid** [comment]
RMK has fixed armada so that the README build instructions work now, and if you're building etnadrm then no galcore headers are required so we can close this now.

The fun isn't over for me yet though as RMK believes I've hit a kernel bug with imxdrm...
